### ISSUE TITLE
Favicon not shown while viewing posts

### ISSUE THREAD

**Issue by ghost** [prami1806/work-at-a-startup#13]
![Screenshot from 2020-12-08 12-29-51](https://user-images.githubusercontent.com/50038824/101452331-8caaba80-3953-11eb-982f-e2dcb7edd85a.png)

**Comment by prami1806** [comment]
Please see if you can see the logo during while navigating from localhost. If yes, it is an AWS issue. Else, we have to have a look at it.

**Comment by ghost** [comment]
Local Host has same issue 

![Screenshot from 2020-12-08 12-52-33](https://user-images.githubusercontent.com/50038824/101452813-50c42500-3954-11eb-83ca-dcc41e7c27fe.png)
